services:
  client:
    container_name: it-shop-client
    build:
      context: .
      dockerfile: ./apps/client/Dockerfile
    depends_on:
      - api

  api:
    container_name: it-shop-api
    build:
      context: .
      dockerfile: ./apps/api-migration/Dockerfile
